Loan
elliotmitchum/ITC205 pull request #32
Opened 2022-07-27 21:30 UTC by elliotmitchum

Refactors the `Loan` class.

Criteria:

- Evaluate against the class diagram
- Evaluate against the code guidelines
- Project builds and runs

2022-08-01 08:38 UTC, elliotmitchum commented
@amrmosit This is ready for review.

2022-08-01 12:43 UTC, amrmosit commented
Thanks @elliotmitchum 
Hey @haynescrossley, this PR is ready for review.
Code is operational (Checked)

2022-08-02 04:14 UTC, haynescrossley commented on src/library/entities/Loan.java
> +    private Date date;
[Class diagram](https://interact2.csu.edu.au/webapps/blackboard/execute/content/file?cmd=view&content_id=_5279818_1&course_id=_63244_1) has this Date variable listed as dueDate. Please refactor/rename.

2022-08-02 04:16 UTC, haynescrossley commented on src/library/entities/Loan.java
> +        return date;
I assume this should return dueDate instead of date. This should be fixed with the refactor/rename above.

2022-08-02 04:18 UTC, haynescrossley requested changes
Only one class variable name to refactor/rename in line with class diagram. Otherwise good to go.
Cheers,
Haynes

2022-08-02 21:53 UTC, haynescrossley approved these changes
Changes approved. Ready for merge @amrmosit.

Changes addressed via commit:

Rename date to dueDate
e724d70

2022-08-02 22:33 UTC, merged

2022-08-02 22:34 UTC, amrmosit commented
Loan has been merged into master