Item
elliotmitchum/ITC205 pull request #33
Opened 2022-07-27 21:52 UTC by elliotmitchum

Refactors the`Item` class and the `ItemType` enum.

Criteria:

- Evaluate against the class diagram
- Evaluate against the code guidelines
- Project builds and runs

2022-07-28 08:30 UTC, elliotmitchum commented on .editorconfig
> +indent_style = space
Test comment

2022-08-01 08:38 UTC, elliotmitchum commented
@amrmosit This is ready for review.

2022-08-01 12:48 UTC, amrmosit commented
Hey @haynescrossley 
This PR is ready for review. 
Code is still operational. (Checked)

2022-08-02 04:03 UTC, haynescrossley commented on src/library/entities/Item.java
> +    public ItemType getType() {
class diagram has this method listed as getItemType(). Please refactor/rename method name.

2022-08-02 04:04 UTC, haynescrossley commented on src/library/entities/Item.java
> +    public void takeout() {
Please refactor/rename with camelCase. Class diagram has takeOut()

2022-08-02 04:04 UTC, haynescrossley commented on src/library/entities/Item.java
> +    public void takeback(boolean damaged) {
Please refactor/rename with camelCase. Class diagram has takeBack()

2022-08-02 04:11 UTC, haynescrossley requested changes
@elliotmitchum please check my comments. Only a couple of method names need to be changed to camelcase and one that didnt match the class diagram/definitions. Cheers, Haynes.

2022-08-02 21:50 UTC, haynescrossley approved these changes, later dismissed
Ready for merge. I'm happy with the changes made.
Changes addressed via commits: 

Rename type to itemType
832113d

Rename takeout to takeOut
bd7a500

Rename takeback to takeBack
275241e

Main has been merged into this branch with the library changes, so this is ready to merge into main @amrmosit.

2022-08-02 23:18 UTC, amrmosit commented
@elliotmitchum @haynescrossley 
There are some conflicts to be resolved after merging loan branch

2022-08-02 23:35 UTC, haynescrossley approved these changes
PR has been updated with latest version of Master (i.e., after Loan was merged).

Ready now to merge into main @amrmosit

2022-08-02 23:51 UTC, merged

2022-08-02 23:52 UTC, amrmosit commented
i1-item-2 branch has been merged